baseURL = 'https://jabeztho.com'
languageCode = 'en-us'
title = 'Jabez Tho'
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = 'UA-149939850-1'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



